# This is a basic workflow to help you get started with Actions

name: Gstreamer-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: nuget/setup-nuget@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Get onevpl
        run: |
          nuget install onevpl.devel.win-x64
      # Runs a set of commands using the runners shell
      - name: Compile gstreamer
        run: |
         git clone https://gitlab.freedesktop.org/gstreamer/gstreamer
         pip3 install meson
         cd gstreamer
         meson setup -Dbad=enabled -Dgst-plugins-bad:msdk=enabled builddir
         meson compile -C builddir
